save_path: 'generated_midi/generated.mid'
condition_file:
length: 500
threshold_len: 500

experiment: 'embedding256-layer6'
max_seq: 2048
embedding_dim: 256
num_layers: 6
event_dim: 388
fp16:
